main: cc.carm.plugin.timereward.Main
name: TimeReward
version: ${project.version}
authors:
  - CarmJos
  - Yurinann
website: ${project.url}
description: ${project.description}

api-version: 1.13

softdepend:
  - PlaceholderAPI

permissions:
  "TimeReward.admin":
    description: "在线自动领奖的管理员权限。"
    default: op

commands:
  "TimeReward":
    permission: "TimeReward.admin"
    description: "在线自动领奖的基础指令。"
    usage: "/TimeReward help"
    aliases:
      - tr